deployment:
  dev:
      branch: master
      commands:
        - heroku config:set CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM --app shuttl-me-eu-dev
        - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
        - git push -f git@heroku.com:secure-basin-79273.git $CIRCLE_SHA1:refs/heads/master